### ISSUE TITLE
Representation of URIs

### ISSUE THREAD

**Issue by alexanderkiel** [cognitect/transit-java#13]
Is there a reason why `java.net.URI` is not used to read values tagged with `r`? I have to convert the special Transit URIs back to a string to be able to do anything useful with them.

**Comment by dchelimsky** [comment]
The reason is that java.net.URI's are more expensive to create and lots of consumers just want strings. If you want java.net.URI, you could write a custom read handler. The write handler already knows how to write java.net.URI or transit.URI to transit.

It's also conceivable that we could add an .e.g `getURI` method to the transit.URI, but you'd still need to do that conversion explicitly, so you're probably better off w/ a custom handler. WDYT?

**Comment by alexanderkiel** [comment]
@dchelimsky You are right. The creation of a java.net.URI is expensive. It's about 500 ns on my laptop tested with criterium. I never really thought about this.

In my use case I like to resolve relative URI's from Transit messages to absolute ones. java.net.URI gives me that. I'm happy with a custom read handler which I already use. A `getURI` method would look rather awkward in a URI class :)

If you like, you could add some documentation to the URI interface to explain the reasoning behind its existence. Otherwise, this issue can be closed.

**Comment by dchelimsky** [comment]
Javadoc updated: https://github.com/cognitect/transit-java/commit/d45b6746780addfae401c8c5f1dd80908fee3c78

**Comment by alexanderkiel** [comment]
Thanks @dchelimsky

**Comment by dchelimsky** [comment]
You're welcome - sorry it took 19 months!
